### ISSUE TITLE
toJS can be used to support nested undo

### ISSUE THREAD

**Issue by kubk** [httptoolkit/mobx-shallow-undo#2]
Hello, thank you for the nice package. I like its simplicity 👍 

The README states that this package doesn't support nested values and suitable only for simple cases:

> This does not handle mutations inside the value or track undo states recursively, it just tracks the shallow undo/redo state of an observable (if you want to add undo/redo in any state anywhere though immutability is strongly recommended, or you're going to have a very bad time!)

But since the library uses `reaction` internally it actually can track nested changes via `toJS` function. Working example: https://codesandbox.io/s/stupefied-snowflake-ts6x75?file=/index.js

It handles both appending to array and editing an item inside the array.

Should the README be updated? I believe at least a tiny notice would be nice.

**Comment by pimterry** [comment]
Ah, interesting. I think that text is still correct, it's just that this is a neat way to explicitly observe the entire state. Perhaps "...by default" would be more accurate.

A PR to the README to explain that more clearly and document how to use `.toJS()` to work around it with your example would be welcome!
